<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>practice-distribution</artifactId>
    <packaging>jar</packaging>

    <parent>
        <groupId>dev.nandi0813</groupId>
        <artifactId>practice-parent</artifactId>
        <version>6.4.6-SNAPSHOT</version>
    </parent>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <server.path.old>./target</server.path.old>
        <server.path.modern>./target</server.path.modern>
    </properties>

    <dependencies>
        <dependency>
            <groupId>dev.nandi0813</groupId>
            <artifactId>practice-core</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>dev.nandi0813</groupId>
            <artifactId>practice-spigot_modern</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>dev.nandi0813</groupId>
            <artifactId>practice-spigot_1_8_8</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>clean install</defaultGoal>
        <finalName>ZonePractice Pro v6.4.6-SNAPSHOT</finalName>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>

                            <artifactSet>
                                <excludes>
                                    <exclude>org.intellij</exclude>
                                    <exclude>org.jetbrains</exclude>
                                </excludes>
                            </artifactSet>

                            <relocations>
                                <relocation>
                                    <pattern>net.megavex.scoreboardlibrary</pattern>
                                    <shadedPattern>dev.nandi0813.practice.dependencies.sidebar</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>dev.dejvokep.boostedyaml</pattern>
                                    <shadedPattern>dev.nandi0813.practice.dependencies.boostedyaml</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.wesjd.anvilgui</pattern>
                                    <shadedPattern>dev.nandi0813.practice.dependencies.anvilgui</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>dev.nandi0813.license</pattern>
                                    <shadedPattern>dev.nandi0813.practice.dependencies.license</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>dev.nandi0813.practice.dependencies.bstats</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>auto-deploy</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy-jar-to-test-servers</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <echo message="Copying plugins for the test servers..." />

                                        <copy file="${project.build.directory}/${project.build.finalName}.jar"
                                              tofile="${server.path.old}/plugins/ZonePracticePro.jar"
                                              overwrite="true" failonerror="false" />

                                        <copy file="${project.build.directory}/${project.build.finalName}.jar"
                                              tofile="${server.path.modern}/plugins/ZonePracticePro.jar"
                                              overwrite="true" failonerror="false" />
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>