<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.nandi0813</groupId>
        <artifactId>practice-parent</artifactId>
        <version>6.4.6-SNAPSHOT</version>
    </parent>

    <artifactId>practice-core</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <dependencies>
        <!-- JSON -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20231013</version>
        </dependency>

        <!-- Paper Spigot -->
        <dependency>
            <groupId>org.github.paperspigot</groupId>
            <artifactId>paperspigot-api</artifactId>
            <version>1.8.8-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <!-- Scoreboard API -->
        <dependency>
            <groupId>net.megavex</groupId>
            <artifactId>scoreboard-library-api</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>net.megavex</groupId>
            <artifactId>scoreboard-library-implementation</artifactId>
            <version>2.7.0</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Placeholder API -->
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.7</version>
            <scope>provided</scope>
        </dependency>

        <!-- API -->
        <dependency>
            <groupId>com.github.ZoneDevelopement</groupId>
            <artifactId>ZonePracticePro-Api</artifactId>
            <version>2.2.0</version>
        </dependency>

        <!-- TAB API -->
        <dependency>
            <groupId>com.github.NEZNAMY</groupId>
            <artifactId>TAB-API</artifactId>
            <version>5.5.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>